---

# use environment variables to set AWS EC2 creds

- hosts: "{{ target|default('localhost') }}"
  tasks:
  - name: launch 3 instances
    ec2:
      key_name: "{{ key_name }}" 
      region: "{{ region }}" 
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}" 
      wait: yes
      group: "{{ secgroup }}" 
      count: 3
      assign_public_ip: yes

  - name: gather facts 
    ec2_remote_facts: 
      region: us-east-1
      filters:
        instance-state-name: running
    register: ec2_info
    tags:
    - generate-files
  
  - name: debug ec2_info output
    debug: msg="{{ item.id }} {{ item.public_dns_name }}"
    with_items: "{{ ec2_info.instances }}"
    when: debug is defined

  - name: write the inventory file
    template: src="./inv.j2" dest="{{ playbook_dir }}/{{ repset_name }}.inv"
    tags:
    - generate-files

  - name: write delete runbook
    template: src="./delete_instances.yml.j2" dest="{{ playbook_dir }}/delete_instances.yml"
    tags:
    - generate-files

  - name: write group vars for mongo repset group
    template: src="./group_vars.j2" dest="{{ playbook_dir }}/group_vars/{{ repset_name }}"
    tags:
    - generate-files
